# Generated by Django 4.2.11 on 2025-03-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stations_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chargingstation',
            table='Final_EV_stations',
        ),
    ]
